AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: feature availability api - get config
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  GetEntityConfigFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: feature_availability/
      Handler: app.lambda_handler
      Runtime: python3.6
      Environment:
        Variables:
          FA_TABLE_NAME: feature-availability
      Policies:
        - arn:aws:iam::348403518528:policy/AWSApiGatewayExecuteRole-DynamoDBReadyOnly

      Events:
        GetEntityConfigEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{entity}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetEntityConfigAPI:
    Description: "API Gateway endpoint URL for Prod stage for Feature Available - Get Config function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{entity}"
  GetEntityConfigFunction:
    Description: "Lambda Function - Feature Availability - Get Config ARN"
    Value: !GetAtt GetEntityConfigFunction.Arn
  GetEntityConfigFunctionIamRole:
    Description: "Implicit IAM Role created for Lambda Function - Feature Availability - Get Config"
    Value: !GetAtt GetEntityConfigFunctionRole.Arn
